spring:
  application:
    name: ms-service-registry
  profiles:
    active: dev
  config:
    import: configserver:http://user:s3cr3t@172.18.0.2:8081

#logging:
#  level:
#    com:
#      netflix:
#        eureka: DEBUG
#        discovery: DEBUG 